exports.voices = [ { Gender: 'Female',
       Id: 'Joanna',
       LanguageCode: 'en-US',
       LanguageName: 'English',
       Name: 'Joanna' },
     { Gender: 'Male',
       Id: 'Miguel',
       LanguageCode: 'es-US',
       LanguageName: 'Spanish',
       Name: 'Miguel' },
     { Gender: 'Female',
       Id: 'Mizuki',
       LanguageCode: 'ja-JP',
       LanguageName: 'Japanese',
       Name: 'Mizuki' },
     { Gender: 'Female',
       Id: 'Filiz',
       LanguageCode: 'tr-TR',
       LanguageName: 'Turkish',
       Name: 'Filiz' },
     { Gender: 'Female',
       Id: 'Astrid',
       LanguageCode: 'sv-SE',
       LanguageName: 'Swedish',
       Name: 'Astrid' },
     { Gender: 'Male',
       Id: 'Maxim',
       LanguageCode: 'ru-RU',
       LanguageName: 'Russian',
       Name: 'Maxim' },
     { Gender: 'Female',
       Id: 'Carmen',
       LanguageCode: 'ro-RO',
       LanguageName: 'Romanian',
       Name: 'Carmen' },
     { Gender: 'Female',
       Id: 'Ines',
       LanguageCode: 'pt-PT',
       LanguageName: 'Portuguese',
       Name: 'Inês' },
     { Gender: 'Female',
       Id: 'Maja',
       LanguageCode: 'pl-PL',
       LanguageName: 'Polish',
       Name: 'Maja' },
     { Gender: 'Male',
       Id: 'Ruben',
       LanguageCode: 'nl-NL',
       LanguageName: 'Dutch',
       Name: 'Ruben' },
     { Gender: 'Female',
       Id: 'Liv',
       LanguageCode: 'nb-NO',
       LanguageName: 'Norwegian',
       Name: 'Liv' },
     { Gender: 'Male',
       Id: 'Giorgio',
       LanguageCode: 'it-IT',
       LanguageName: 'Italian',
       Name: 'Giorgio' },
     { Gender: 'Male',
       Id: 'Karl',
       LanguageCode: 'is-IS',
       LanguageName: 'Icelandic',
       Name: 'Karl' },
     { Gender: 'Male',
       Id: 'Mathieu',
       LanguageCode: 'fr-FR',
       LanguageName: 'French',
       Name: 'Mathieu' },
     { Gender: 'Female',
       Id: 'Marlene',
       LanguageCode: 'de-DE',
       LanguageName: 'German',
       Name: 'Marlene' },
     { Gender: 'Female',
       Id: 'Naja',
       LanguageCode: 'da-DK',
       LanguageName: 'Danish',
       Name: 'Naja' },
     { Gender: 'Female',
       Id: 'Gwyneth',
       LanguageCode: 'cy-GB',
       LanguageName: 'Welsh',
       Name: 'Gwyneth' }]